# Generated by Django 5.2.7 on 2025-10-21 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='employment_type',
            field=models.CharField(choices=[('casual', 'Casual'), ('contract', 'Contract')], default='casual', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
    ]
